# -*- coding: utf-8 -*-
"""Day_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v1NcEW8rmUuRPgEMJJqTZKcBmcZEzj3R
"""

# Operators in Python
# 1.Arithmetic Operator
# 2.Relational opeartor
# 3.Logical Operator
# 4.Bitwise Operator
# 5.Assignment Operators
# 6.Membership Operators

# 1. Arithmetic Operator
print(3+2)
print(5-2)
print(3*5)
print(5/2)
print(5//2)
print(5%2)
print(5**2)

# Relational Operator (Basically compared)
print(4>3)
print(3<5)
print(2==2)
print(3>=4)
print(5>=4)
print(4!=3)

#Logical Operator
print(0 and 1)
print(0 or 1)
print(not 0)

# Bitwise Operator (Binary Representation)

# Bitwise and
print(2 & 3)

# Bitwise or
print(2 | 3) #Or

# Bitwise Xor
print(2 ^ 3)

# Assignment Operator
a = 2
print(a)

# a = a + 2

a += 2
print(a)

# a++ or ++a not used in python because is ambiguity

# Membership Operator

# in/not in

print("D" in "Dallas")

print(1 in [2,3,4,6,1])
print(3 not in [2,5,6,7,3])

# enter 3 digit
number = int(input("Plz enter 3 didgit"))
print(number)

"""### If/Else in Python"""

# 1.-> login and indentation
# 2.email->gulzi
# 3.password->1234

email = input("plz enter email: ")
password = input("plz enter password: ")

if email == "gulzi" and password == "1234":
  print("You are successful login")

elif email == "gulzi" and password != "1234":
  print("Your password is incorrect")
  password = input("plz enter password again")
  if password == "1234":
    print("finall login successfully")
  else:
    print("ap se nahi ho paayega")

else:
  print("your input is  wrong")

# find min from 3 numbers

a = input("plz enter 1st number: ")
b = input("plz enter 2nd number: ")
c = input("plz enter 3rd number: ")

if a<b and a<c:
  print("The smallest number is", a)
elif b<c:
  print("The smallest number is", b)
else:
  print("The smallest number is", c)

# menu driven calculator program
first_number = int(input("plz enter 1st number"))
second_number = int(input("plz enter 2nd number"))

print("plz select operation +, -, *, /")

op = input("Plz enter operation")

if op == "+":
 print(first_number + second_number)
elif op == "-":
  print(first_number - second_number)
elif op == "*":
  print(first_number * second_number)
elif op == "/":
 print(first_number / second_number)

# menu driven program
menu = input('''
How I can help you!.
1. Enter 1 for pin change
2. Enter 2 for balance
3. Enter 3 for withdrawl
4. Enter 4 for exit
''')

if menu == "1":
  print("pin change")
elif menu == "2":
  print("balance check")
elif menu == "3":
  print("withdrawl")
else:
  print("Exit")

# Modules in python
# 1.math
# 2.keyword
# 3.constant
# 4.random

# 1.math

import math
math.floor(6.8)

math.sqrt(196)

# 2. Keyword
import keyword
print(keyword.kwlist)

# 3.random
import random
print(random.randint(1,100))

import datetime
print(datetime.datetime.now())

help('modules')



"""Loop in python
1. Need for loop
2.while loop
3.for loop
"""

# while loop
# number = int(input("Plz enter number"))

# i = 1
# while i<11:
#   print(number*i)
#   i +=1

# number = int(input("Plz enter number for multiplicatio: "))

# i=1
# while i<11:
#   print(number, "X", i, "=", number*i)
#   i+=1

number = int(input("plz  enter number for multiplication: "))
i=1
while i<11:
  print(number, "X", i, "=", number*i)
  i+=1

# while loop with else (if loop break then print else statement)

i = 1
while i<3:
  print(i)
  i+=1
else:
  print("limit break")

# # Guessing game
# generate number between 1 to 100

import random
jackpot = random.randint(1, 3)

user_input=int(input("plz guess: "))
counter = 1

while user_input!=jackpot:
  if user_input < jackpot:
    print("galat! guess higher: ")
  else:
    print("galat! guess lower: ")

  user_input = int(input("again guess kro: "))
  counter+=1
else:
  print("Success")
  print("attemp",counter)

# for  loop demo
# for i in range(1,10):
#   print(i)

# for reverse iteration
for i in range(10,0,-1):
  print(i)

"""Program: The current population of the town is 10000. The population of the town is increasing at the rate of 10%.find out the population at the end of the each of the last 10 years."""

curr_population = 10000
for i in range(10,0,-1):
  print(i,curr_population)
  curr_population=curr_population/1.1







